services:
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users_service
      - community_service
      - frontend
    networks:
      - backend

  users_service:
    build:
      context: ./services/users
      dockerfile: Dockerfile.dev
    image: users-dev
    env_file:
      - ./services/users/src/.env
    volumes:
      - ./services/users/src:/app
    working_dir: /app
    expose:
      - "8001"
    networks:
      - backend
    depends_on:
      - db_postgres_users

  db_postgres_users:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_users:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  community_service:
    build:
      context: ./services/community
      dockerfile: Dockerfile.dev
    image: community-dev
    env_file:
      - ./services/community/src/.env
    volumes:
      - ./services/community/src:/app
    working_dir: /app
    expose:
      - "8002"
    networks:
      - backend
    depends_on:
      - db_postgres_community

  db_postgres_community:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_community:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  publications_service:
    build:
      context: ./services/publications
      dockerfile: Dockerfile.dev
    image: publications-dev
    env_file:
      - ./services/publications/src/.env
    volumes:
      - ./services/publications/src:/app
    working_dir: /app
    expose:
      - "8002"
    networks:
      - backend
    depends_on:
      - db_postgres_publications
      - users_service

  db_postgres_publications:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata_publications:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend

  #  CHAT SERVICE
  chat_service:
    build:
      context: ./services/chat
      dockerfile: Dockerfile.dev
    command: air        
    image: chat-dev
    volumes:
      - ./services/chat:/app 
    working_dir: /app
    expose:
       - "8004:8004"
    networks:
      - backend
    depends_on:
      - users_service
      - mongo_chat
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=chatdb

  mongo_chat:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  # FRONTEND
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: antoniotorres841@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db_postgres_users
      - db_postgres_community
      - db_postgres_publications
    networks:
      - backend

volumes:
  pgdata_users:
  pgdata_community:
  pgdata_publications:
  mongo_data:
  pgadmin:

networks:
  backend:
    driver: bridge
