FROM golang:1.24-alpine

RUN apk add --no-cache git

# (NO uses USER appuser aquí todavía)

WORKDIR /app

# Instala Air como root (importante)
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download


CMD ["air"]
